### ISSUE TITLE
extract_parameter_set_dials() fails for self-written gbm engine for boost_tree()

### ISSUE THREAD

**Issue by Npaffen** [tidymodels/parsnip#707] opened 2022-04-27 07:03 UTC
This issue is related to https://github.com/tidymodels/parsnip/issues/220 since I extracted most of the code for the gbm machine and turned it into an engine for boost_tree().

This issue was also posted on [Stack](https://stackoverflow.com/questions/72015727/make-gbm-tuneable-with-parsnip), so I can help the community easier by cross-posting a possible solution which might come up here faster.

I followed [this vignette](https://www.tidymodels.org/learn/develop/models/) of the `tidymodels` package to make the `gbm` an engine for the `boost_tree()` function.

I came up with the following for regression tasks:

  ```
  library(tidyverse)
    library(tidymodels)
    library(workflow)
    library(tune)
    install.packages(gbm) #just install do not load
    {
        set_model_engine(
          model = "boost_tree", 
          mode  = "regression", 
          eng  = "gbm"
        )
        set_dependency("boost_tree", eng = "gbm", pkg = "gbm")
        set_model_arg(
          model        = "boost_tree", 
          eng          = "gbm", 
          parsnip      = "trees", 
          original     = "n.trees",
          func         = list(pkg = "gbm", fun = "gbm"),
          has_submodel = TRUE
        )
        set_model_arg(
          model        = "boost_tree", 
          eng          = "gbm", 
          parsnip      = "tree_depth", 
          original     = "interaction.depth", 
          func         = list(pkg = "gbm", fun = "gbm"), 
          has_submodel = TRUE
        )
        set_model_arg(
          model        = "boost_tree", 
          eng          = "gbm", 
          parsnip      = "learn_rate", 
          original     = "shrinkage", 
          func         = list(pkg = "gbm", fun = "gbm"), 
          has_submodel = TRUE
        )
        
        set_encoding(
          model = "boost_tree",
          eng = "gbm",
          mode = "regression",
          options = list(
            predictor_indicators = "none",
            compute_intercept = FALSE,
            remove_intercept = FALSE,
            allow_sparse_x = FALSE
          )
        )
        
        gbm <- function(mode = "regression", trees = NULL, 
                        tree_depth = NULL, learn_rate = NULL, cv.folds = 1) {
          # make sure mode is regression
          if(mode != "regression") {
            stop("`mode` should be 'regression'", call. = FALSE)
          }
          
          # capture argument in quosures
          args <- list(
            trees      = rlang::enquo(trees), 
            tree_depth = rlang::enquo(tree_depth), 
            learn_rate = rlang::enquo(learn_rate)
          )
          
          # empty slots for future parts of specification
          out <- list(args = args, eng_args = NULL, 
                      mode = mode, method = NULL, engine = NULL)
          
          # set class in correct order
          class(out) <- make_classes("gbm")
          out
        }
        
        set_fit(
          model = "boost_tree", 
          eng   = "gbm", 
          mode  = "regression", 
          value = list(
            interface = "formula", # other possible values are "data.frame", "matrix"
            protect = c("formula", "data"), # nonchangeable user-arguments
            func = c(pkg = "gbm", fun = "gbm"), # call gbm::gbm()
            defaults = list(
              distribution = "gaussian", 
              n.cores = NULL, 
              verbose = FALSE
            ) # default argument changeable by user
          )
        )
        
        set_pred(
          model = "boost_tree", 
          eng   = "gbm", 
          mode  = "regression", 
          type  = "numeric", 
          value = list(
            pre = NULL, 
            post = NULL, 
            func = c(fun = "predict"), 
            args = list(
              object = expr(object$fit), 
              newdata = expr(new_data), 
              n.trees = expr(object$fit$n.trees),
              type = "response", 
              single.tree = TRUE
            )
          )
        )
        

  }
```

But if I try to use this engine to tune the hyperparameters using `tune_bayes()` from the `parsnip` package my code fails to extract the parameter set from the workflow:

    ```
rec <- recipe(mpg ~.,mtcars)
    
    model_tune <- parsnip::boost_tree(
            mode = 'regression',
            trees = 1000,
            tree_depth = tune(),
            learn_rate = tune()

    model_wflow <- workflow() %>%
      add_model(model_tune) %>%
      add_recipe(rec)

    
    HP_set <- extract_parameter_set_dials(model_wflow, tree_depth(range = c(1,100)))
    HP_set

```
   

 The function `extract_parameter_set_dials()` always prompts the following error :
    
    ```
Error in `mutate()`:
    ! Problem while computing `object = purrr::map(call_info, eval_call_info)`.
    Caused by error in `.f()`:
    ! Error when calling gbm(): Error in terms.formula(formula, data = data) : 
      argument is not a valid model
```
Maybe this has something to do with the `set_fit()` options in the engine settings but that is just a wild guess.

**How can I use the `gbm` engine for `boost_tree()` and tune the hyperparameter with `tune_bayes()`?**

  [1]: https://www.tidymodels.org/learn/develop/models/

**Comment by topepo** [comment] 2022-04-27 17:01
It was a minor issue. The `set_model_arg()` calls should reference the functions in the dials package (or any other package) that has the parameter functions that you need. 

(also - side note - you don't need a `gbm()` function)

``` r
library(tidymodels)
tidymodels_prefer()
theme_set(theme_bw())

set_model_engine(model = "boost_tree",
                 mode  = "regression",
                 eng  = "gbm")
set_dependency("boost_tree", eng = "gbm", pkg = "gbm")
set_model_arg(
  model        = "boost_tree",
  eng          = "gbm",
  parsnip      = "trees",
  original     = "n.trees",
  func         = list(pkg = "dials", fun = "trees"),  # <- change here
  has_submodel = TRUE
)
set_model_arg(
  model        = "boost_tree",
  eng          = "gbm",
  parsnip      = "tree_depth",
  original     = "interaction.depth",
  func         = list(pkg = "dials", fun = "tree_depth"), # <- change here
  has_submodel = TRUE
)
set_model_arg(
  model        = "boost_tree",
  eng          = "gbm",
  parsnip      = "learn_rate",
  original     = "shrinkage",
  func         = list(pkg = "dials", fun = "learn_rate"), # <- change here
  has_submodel = TRUE
)

set_encoding(
  model = "boost_tree",
  eng = "gbm",
  mode = "regression",
  options = list(
    predictor_indicators = "none",
    compute_intercept = FALSE,
    remove_intercept = FALSE,
    allow_sparse_x = FALSE
  )
)

set_fit(
  model = "boost_tree",
  eng   = "gbm",
  mode  = "regression",
  value = list(
    interface = "formula",
    # other possible values are "data.frame", "matrix"
    protect = c("formula", "data"),
    # nonchangeable user-arguments
    func = c(pkg = "gbm", fun = "gbm"),
    # call gbm::gbm()
    defaults = list(
      distribution = "gaussian",
      n.cores = NULL,
      verbose = FALSE
    ) # default argument changeable by user
  )
)

set_pred(
  model = "boost_tree",
  eng   = "gbm",
  mode  = "regression",
  type  = "numeric",
  value = list(
    pre = NULL,
    post = NULL,
    func = c(fun = "predict"),
    args = list(
      object = expr(object$fit),
      newdata = expr(new_data),
      n.trees = expr(object$fit$n.trees),
      type = "response",
      single.tree = TRUE
    )
  )
)


rec <- recipe(mpg ~ ., mtcars)
model_tune <- parsnip::boost_tree(
  mode = 'regression',
  trees = 1000,
  tree_depth = tune(),
  learn_rate = tune()
) %>%
  set_engine("gbm")

model_wflow <- workflow() %>%
  add_model(model_tune) %>%
  add_recipe(rec)


HP_set <-
  extract_parameter_set_dials(model_wflow, tree_depth(range = c(1, 100)))
HP_set
#> Collection of 2 parameters for tuning
#> 
#>  identifier       type    object
#>  tree_depth tree_depth nparam[+]
#>  learn_rate learn_rate nparam[+]
```

<sup>Created on 2022-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Npaffen** [comment] 2022-04-28 09:27
Thank you @topepo! Is it ok for you if I share your answer to the Stack community, cross-refrencing your answer?

**Comment by Npaffen** [comment] 2022-04-28 16:49
@topepo I cheered to early as it seems. If I try to the followng tune_bayes() setup I recieve another error which I can't get reid of on my own...

`initial <- 4
search_results_bayesian <- tune_bayes(
  model_wflow,                              # workflows object defined above             
  resamples = folds,                        # rset() object defined above
  param_info = HP_set,                      # HP set defined above (updated HP set)
  initial = initial ,                             # intial observations of the loss distribution 
  # max number of search iterations, can be set to a high value
  #since we will hoepfully never reach this due to our control function
  iter = 25,
  metrics = metric_set(yardstick::rmse),            #  
  control = control_bayes(no_improve = 3,   # cutoff for the number of iterations without better results.
                          save_pred = F,  #predictions should not be saved.
                          verbose = TRUE))
`
The resulting stacktrace is the following :
`> rlang::last_trace()
<error/rlang_error>
Error in `FUN()`:
! Can't convert a character `NA` to a symbol.
---
Backtrace:
     x
  1. +-tune::tune_bayes(...)
  2. +-tune:::tune_bayes.workflow(...)
  3. | \-tune:::tune_bayes_workflow(...)
  4. |   \-tune::check_initial(...)
  5. |     +-tune::tune_grid(...)
  6. |     \-tune:::tune_grid.workflow(...)
  7. |       \-tune:::tune_grid_workflow(...)
  8. |         \-tune:::tune_grid_loop(...)
  9. |           \-tune:::compute_grid_info(workflow, grid)
 10. |             \-tune:::compute_grid_info_model(workflow, grid, parameters_model)
 11. |               +-generics::min_grid(spec, grid)
 12. |               \-tune::min_grid.boost_tree(spec, grid)
 13. |                 \-tune:::submod_and_others(grid, fixed_args)
 14. |                   \-... %>% dplyr::ungroup()
 15. +-dplyr::ungroup(.)
 16. +-dplyr::summarize(., max_val = max(..val, na.rm = TRUE))
 17. +-dplyr::group_by(., !!!rlang::syms(fixed_args))
 18. +-dplyr:::group_by.data.frame(., !!!rlang::syms(fixed_args))
 19. | \-dplyr::group_by_prepare(.data, ..., .add = .add, caller_env = caller_env())
 20. |   \-rlang::enquos(..., .ignore_empty = "all")
 21. |     \-rlang:::endots(...)
 22. |       \-rlang:::map(...)
 23. |         \-base::lapply(.x, .f, ...)
 24. |           \-rlang FUN(X[[i]], ...)
 25. |             \-rlang::splice(...)
 26. \-rlang::syms(fixed_args)
 27.   \-rlang:::map(x, sym)
 28.     \-base::lapply(.x, .f, ...)
 29.       \-rlang FUN(X[[i]], ...)
 30.         \-rlang:::abort_coercion(x, "a symbol")
 31.           \-rlang::abort(msg, call = call)`
 
 Can you help again to identify the error or propose a possible solution? Thanks in advance!

**Comment by juliasilge** [comment] 2022-05-04 01:59
The problem is `submodel = TRUE`; if you [turn that off, it works as expected](https://stackoverflow.com/a/72107195/5468471). Does this model support the [submodel trick](https://tune.tidymodels.org/articles/extras/optimizations.html#sub-model-speed-ups)?

**Comment by simonpcouch** [comment] 2022-05-20 15:55
Closing, as it seems this has been resolved. Thanks for the issue!

**Closed by simonpcouch** 2022-05-20 15:55 UTC
