### ISSUE TITLE
Internals bug? `will_make_matrix()` returns `False` when given a matrix

### ISSUE THREAD

**Issue by joeycouse** [tidymodels/parsnip#786] opened 2022-08-14 23:20 UTC
Hello, I'm working on a PR to address #765. While doing so I ran into an issue with `will_make_matrix()`. Shouldn't the return value be True if `y` is a matrix or a vector? 

When `y` is a numeric matrix it fails this check and converts it to a vector. This is stripping the colname of `y` whenever it is passed to function later down the line such as `xgb_train()`

https://github.com/tidymodels/parsnip/blob/f0810910d0b69141af12c66ae210ec0880f95323/R/convert_data.R#L326-L336

**Comment by simonpcouch** [comment] 2022-08-15 17:54
I believe`will_make_matrix` may mean "is this a thing that's _not_ a matrix that will be converted to one," and that first `if (is.matrix) return(FALSE)` line makes me think that may be the case. Seems worth adding a code comment to clarify!

**Comment by joeycouse** [comment] 2022-08-15 18:21
Hmm, based on this comment I would assume the intention is to return `y` as a matrix if it is possible. Right now there doesn't seem to be a case when `y` is return as a matrix, from the call to `.convert_form_to_xy()`

https://github.com/tidymodels/parsnip/blob/f0810910d0b69141af12c66ae210ec0880f95323/R/convert_data.R#L120-L124

**Comment by topepo** [comment] 2022-08-30 13:54
@simonpcouch is right about the intent. 

It was also designed for data frames so that's why there's no logic to handle vectors. We _could_ do this but would have to know how to name that column (so it feels out of scope for this function).  

@joeycouse can you give some context on where this has come up?

**Comment by joeycouse** [comment] 2022-08-30 15:45
@topepo this is comes up when there is a call to `.covert_form_to_xy_fit()` i.e. where the underlying model only has a `x_y` interface. The return value of `y` is always a vector and doesn't carry a name so when passed to the underlying modeling function there is no way to determine what the original column name of `y` was. 

```r

> reg_fit <-
+   boost_tree(trees = 10, mode = "regression") %>%
+   set_engine("xgboost", 
+              eval_metric = "mae", 
+              verbose = 1) %>%
+   fit(mpg ~ ., data = mtcars)
```
This is an issue because the call to `xgb_train()` has no name for `y` which makes it very difficult to extended the `validation` arg to accept a data frame (#771, #765, #760, #471) because there is no good way to determine what the outcome column is. 

https://github.com/tidymodels/parsnip/blob/e1eb30a6f6704bd0a3cf61736ea1d26e1d8eb081/R/fit_helpers.R#L137-L155

**Comment by simonpcouch** [comment] 2022-08-30 18:05
Given that we've confirmed that the function, as it's currently scoped, works as intended, and we've closed the PR that prompted the proposed extension in scope, I'm going to go ahead and close this issue.

**Closed by simonpcouch** 2022-08-30 18:05 UTC
Labels: documentation
