### ISSUE TITLE
extra .md file for removal

### ISSUE THREAD

**Issue by luisDVA** [tidymodels/parsnip#1159] opened 2024-08-20 18:27 UTC
found a loose readme.md file in the R folder that contains some "Notes on the development" of parsnip.
This file is in .buildignore and @topepo said that this content is already on a blog post
Tagging for removal.

**Comment by simonpcouch** [comment] 2024-08-28 14:52
Thanks for the issue! Duplicate of #1149—closing in favor of the earlier issue.

**Closed by simonpcouch** 2024-08-28 14:52 UTC
